service: lambda-nisaba

provider:
  name: aws
  runtime: nodejs6.10
  stage: develop
  region: us-west-2

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

functions:
  phone:
    handler: src/api-v2_handler.phone
    description: Create phone attestations
    events:
     - http:
         path: v2/phone
         method: post
    environment:
      SIGNER_KEY: 746c06333df9d76c533783bb04aea008cb44e48cda1733dafa9eb65302a2e011
      APP_NAME: 'ConsenSys Verification Services (test:ajunge)'
      APP_MNID: '2owhy1rcRzt2DiYd95ov5aKkzyzcJCCJGMG'
